
export const aliases = {
  "ACEITE GIRASOL": "ACEITE DE GIRASOL",
  "CHOCOLATE NESQUIK": "NESQUIK",
  "CAJA TORTERA (CARTON)": "CAJA TORTERA",
  "DLECHE REPOSTERO PERGAMINO": "DULCE REPOSTERO",
  "DULCE DE LECHE REPOSTERO": "DULCE REPOSTERO",
  "ACEITE ESENCIAL LIMON A/L": "ACEITE ESENCIAL DE LIMON",
  "STRACIETELLA BLANCA": "STRACCIATELA BLANCA",

  // idénticos (para consistencia)
  "AZUCAR SUELTA": "AZUCAR SUELTA",
  "AZUCAR IMPALPABLE": "AZUCAR IMPALPABLE",
  "HARINA 0000": "HARINA 0000",
  "HUEVOS": "HUEVOS",
  "MARGARINA": "MARGARINA",
  "RICOTTA": "RICOTTA",
  "POLVO PARA HORNEAR": "POLVO PARA HORNEAR",
  "SAL FINA": "SAL FINA",
  "COBERTURA AMARGA EN POLVO": "COBERTURA AMARGA EN POLVO",
  "COCO RALLADO": "COCO RALLADO",
  "ESENCIA DE VAINILLA": "ESENCIA DE VAINILLA",
  "DULCE DE MEMBRILLO": "DULCE MEMBRILLO",
  "DULCE DE BATATA": "DULCE BATATA",
  "NUEZ PELADA": "NUEZ PELADA",
  "PASAS DE UVA RUBIA": "PASAS DE UVA RUBIA",
  "MICROGALLETITAS": "MICROGALLETITAS",

  // insumos que no están en tu lista → sin código
  "LIMON": null,
  "COLORANTE AMARILLO 1002": null,
  "GELATINA SIN SABOR": null,
  "CREMA DE LECHE": null,
  "CREMA DE LECHE AL 39 %": null,
  "MANZANA VERDE": null,
  "OPORTO": null,
   "JUGO TANG SABOR MANZANA": null,
  "BANANA": null,
  "BUDINERA B60 DESCARTABLE": "BUDINERA ALUMINIO"
}