

export const recetas = [
  {
    mercaderia: "BUDIN DE COCO X 5 RAC",
    ingredientes: [
      { nombre: "LIMON", cantidad: 0.002 },
      { nombre: "LECHE ENTERA", cantidad: 0.020 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.091 },
      { nombre: "COBERTURA AMARGA EN POLVO", cantidad: 0.004 },
      { nombre: "HARINA 0000", cantidad: 0.091 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.003 },
      { nombre: "SAL FINA", cantidad: 0.007 },
      { nombre: "HUEVOS", cantidad: 0.057 },
      { nombre: "AZUCAR IMPALPABLE", cantidad: 0.015 },
      { nombre: "BUDINERA B60 DESCARTABLE", cantidad: 1.0 },
      { nombre: "ACEITE GIRASOL", cantidad: 0.04 }
    ]
  },
  {
    mercaderia: "BUDIN DE LIMON X 5 RAC",
    ingredientes: [
      { nombre: "LIMON", cantidad: 0.002 },
      { nombre: "LECHE ENTERA", cantidad: 0.014 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.092 },
      { nombre: "HARINA 0000", cantidad: 0.092 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.003 },
      { nombre: "HUEVOS", cantidad: 0.057 },
      { nombre: "AZUCAR IMPALPABLE", cantidad: 0.015 },
      { nombre: "ACEITE ESENCIAL LIMON A/L", cantidad: 0.0004 },
      { nombre: "COLORANTE AMARILLO 1002", cantidad: 0.002 },
      { nombre: "BUDINERA B60 DESCARTABLE", cantidad: 1.0 },
      { nombre: "ACEITE DE GIRASOL", cantidad: 0.040 },
      { nombre: "SAL FINA", cantidad: 0.007 }
    ]
  },
  {
    mercaderia: "CUADRADITO DE DULCE DE LECHE",
    ingredientes: [
      { nombre: "AZUCAR SUELTA", cantidad: 0.011 },
      { nombre: "HARINA 0000", cantidad: 0.022 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.005 },
      { nombre: "MARGARINA", cantidad: 0.011 },
      { nombre: "DLECHE REPOSTERO PERGAMINO", cantidad: 0.035 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "CUADRADITO DE PASTA FROLA",
    ingredientes: [
      { nombre: "AZUCAR SUELTA", cantidad: 0.011 },
      { nombre: "HARINA 0000", cantidad: 0.022 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.005 },
      { nombre: "DULCE DE MEMBRILLO", cantidad: 0.035 },
      { nombre: "MARGARINA", cantidad: 0.011 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "CUADRADITOS BROWNIES",
    ingredientes: [
      { nombre: "LECHE ENTERA", cantidad: 0.009460317 },
      { nombre: "CHOCOLATE EN BARRA", cantidad: 0.003490727 },
      { nombre: "CHOCOLATE NESQUIK", cantidad: 0.00750539 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.016 },
      { nombre: "HARINA 0000", cantidad: 0.010 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.0 },
      { nombre: "HUEVOS", cantidad: 0.006 },
      { nombre: "MARGARINA", cantidad: 0.006 },
      { nombre: "NUEZ PELADA", cantidad: 0.003 },
      { nombre: "CAJA TORTERA (CARTON)", cantidad: 0.0 },
      { nombre: "ACEITE DE GIRASOL", cantidad: 0.003 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.001 },
      { nombre: "SAL FINA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "CUADRADITOS DE BATATA",
    ingredientes: [
      { nombre: "AZUCAR SUELTA", cantidad: 0.011 },
      { nombre: "HARINA 0000", cantidad: 0.022 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.005 },
      { nombre: "DULCE DE BATATA", cantidad: 0.035 },
      { nombre: "MARGARINA", cantidad: 0.011 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "CUADRADITOS DE RICOTA Y D.LECHE",
    ingredientes: [
      { nombre: "RICOTTA", cantidad: 0.026 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.015 },
      { nombre: "HARINA 0000", cantidad: 0.018 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.004 },
      { nombre: "MARGARINA", cantidad: 0.009 },
      { nombre: "DLECHE REPOSTERO PERGAMINO", cantidad: 0.026 },
      { nombre: "CREMA DE LECHE POTE FAMILIAR", cantidad: 0.0 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "CUADRADITO PIE DE MANZANACON TAPA",
    ingredientes: [
      { nombre: "OPORTO", cantidad: 0.001 },
      { nombre: "MANZANA DESHIDRATADA", cantidad: 0.007 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.017 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 },
      { nombre: "HARINA 0000", cantidad: 0.018 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.004 },
      { nombre: "MARGARINA", cantidad: 0.009 },
      { nombre: "NUEZ PELADA", cantidad: 0.001 },
      { nombre: "PASAS DE UVA RUBIA", cantidad: 0.001 },
      { nombre: "JUGO TANG SABOR MANZANA", cantidad: 0.0 },
      { nombre: "GELATINA SIN SABOR", cantidad: 0.0 },
      { nombre: "MAICENA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "CUADRADITO DE MANZANA",
    ingredientes: [
      { nombre: "LECHE ENTERA", cantidad: 0.004541407 },
      { nombre: "CREMA DE LECHE AL 39 %", cantidad: 0.007843915 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.011619258 },
      { nombre: "HARINA 0000", cantidad: 0.016321968 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.000489659 },
      { nombre: "HUEVOS", cantidad: 0.003329682 },
      { nombre: "MANZANA VERDE", cantidad: 0.023982221 },
      { nombre: "MARGARINA", cantidad: 0.008160984 },
      { nombre: "CREMA DE LECHE POTE FAMILIAR", cantidad: 0.007843915 },
      { nombre: "MAICENA", cantidad: 0.003298843 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 4.01347e-05 }
    ]
  },
  {
    mercaderia: "CUADRADITO DE RICOTTA",
    ingredientes: [
      { nombre: "RICOTTA", cantidad: 0.046485261 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.011256236 },
      { nombre: "HARINA 0000", cantidad: 0.018450921 },
      { nombre: "HUEVOS", cantidad: 0.003763988 },
      { nombre: "MARGARINA", cantidad: 0.00922546 },
      { nombre: "CREMA DE LECHE", cantidad: 0.000798186 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.000553528 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 4.53697e-05 }
    ]
  },
  {
    mercaderia: "CUADRADITO DE DULCE DE LECHE (VARIANTE COCO)",
    ingredientes: [
      { nombre: "AZUCAR SUELTA", cantidad: 0.011 },
      { nombre: "HARINA 0000", cantidad: 0.022 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.007 },
      { nombre: "HUEVOS", cantidad: 0.005 },
      { nombre: "MARGARINA", cantidad: 0.011 },
      { nombre: "DLECHE REPOSTERO PERGAMINO", cantidad: 0.035 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.005 },
      { nombre: "COCO RALLADO", cantidad: 0.180 }
    ]
  },
  {
    mercaderia: "HAVANET",
    ingredientes: [
      { nombre: "Harina 0000", cantidad: 0.022 },
      { nombre: "Huevo", cantidad: 0.005 },
      { nombre: "Margarina", cantidad: 0.009 },
      { nombre: "Azucar", cantidad: 0.011 },
      { nombre: "Polvo de Hornear", cantidad: 0.002 },
      { nombre: "Esencia Vainilla", cantidad: 0.002 },
      { nombre: "Cacao Amargo", cantidad: 0.006 },
      { nombre: "Dulce de Leche", cantidad: 0.026 },
      { nombre: "Chocolate en Barra", cantidad: 0.004 },
      { nombre: "Aceite de Girasol", cantidad: 0.002 }
    ]
  },
  {
    mercaderia: "MARROC",
    ingredientes: [
      { nombre: "Harina 0000", cantidad: 0.007 },
      { nombre: "Huevo", cantidad: 0.044 },
      { nombre: "Margarina", cantidad: 0.003 },
      { nombre: "Azucar", cantidad: 0.002 },
      { nombre: "Polvo de Hornear", cantidad: 0.0 },
      { nombre: "Esencia Vainilla", cantidad: 0.0 },
      { nombre: "Cacao Amargo", cantidad: 0.001 },
      { nombre: "Pasta de Mani", cantidad: 0.012 },
      { nombre: "Chocolate en Barra", cantidad: 0.012 }
    ]
  },
  {
    mercaderia: "HAVANET BLANCO",
    ingredientes: [
      { nombre: "Harina 0000", cantidad: 0.007 },
      { nombre: "Huevo", cantidad: 0.002 },
      { nombre: "Margarina", cantidad: 0.003 },
      { nombre: "Azucar", cantidad: 0.002 },
      { nombre: "Polvo de Hornear", cantidad: 0.0 },
      { nombre: "Esencia Vainilla", cantidad: 0.0 },
      { nombre: "Cacao Amargo", cantidad: 0.001 },
      { nombre: "Dulce de Leche", cantidad: 0.024 },
      { nombre: "STRACIETELLA BLANCA", cantidad: 0.005 }
    ]
  },
  {
    mercaderia: "BUDIN F/ROJOS",
    ingredientes: [
      { nombre: "LIMON", cantidad: 0.002 },
      { nombre: "LECHE ENTERA", cantidad: 0.020 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.091 },
      { nombre: "MIX DE FRUTOS ROJOS CONGELADOS", cantidad: 0.004 },
      { nombre: "HARINA 0000", cantidad: 0.091 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.003 },
      { nombre: "SAL FINA", cantidad: 0.007 },
      { nombre: "HUEVOS", cantidad: 0.057 },
      { nombre: "AZUCAR IMPALPABLE", cantidad: 0.015 },
      { nombre: "BUDINERA B60 DESCARTABLE", cantidad: 1.0 },
      { nombre: "ACEITE GIRASOL", cantidad: 0.04 }
    ]
  },
  {
    mercaderia: "BUDIN CHOCOLATE",
    ingredientes: [
      { nombre: "LIMON", cantidad: 0.002 },
      { nombre: "LECHE ENTERA", cantidad: 0.020 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.091 },
      { nombre: "COBERTURA AMARGA EN POLVO", cantidad: 0.013 },
      { nombre: "HARINA 0000", cantidad: 0.091 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.003 },
      { nombre: "SAL FINA", cantidad: 0.007 },
      { nombre: "HUEVOS", cantidad: 0.057 },
      { nombre: "BUDINERA B60 DESCARTABLE", cantidad: 1.0 },
      { nombre: "ACEITE GIRASOL", cantidad: 0.036 }
    ]
  },
  {
    mercaderia: "CUADRADITOS DE RICOTA Y F/ROJOS",
    ingredientes: [
      { nombre: "RICOTTA", cantidad: 0.026 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.015 },
      { nombre: "HARINA 0000", cantidad: 0.018 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.004 },
      { nombre: "MARGARINA", cantidad: 0.009 },
      { nombre: "MIX DE FRUTOS ROJOS CONGELADOS", cantidad: 0.026 },
      { nombre: "CREMA DE LECHE POTE FAMILIAR", cantidad: 0.0 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 }
    ]
  },
  {
    mercaderia: "Carrot cake",
    ingredientes: [
      { nombre: "Huevo (KG)", cantidad: 0.007 },
      { nombre: "Azucar", cantidad: 0.011 },
      { nombre: "Miel", cantidad: 0.006 },
      { nombre: "Aceite de girasol", cantidad: 0.008 },
      { nombre: "Harina 0000", cantidad: 0.013 },
      { nombre: "Polvo para hornear", cantidad: 0.001 },
      { nombre: "Nueces", cantidad: 0.002 },
      { nombre: "Canela molida", cantidad: 0.0 },
      { nombre: "Nuez moscada", cantidad: 0.0 },
      { nombre: "Sal fina", cantidad: 0.0 },
      { nombre: "Zanahoria Rallada", cantidad: 0.019 }
    ]
  },
  {
    mercaderia: "Pasta  frola de chocolate",
    ingredientes: [
      { nombre: "AZUCAR SUELTA", cantidad: 0.011 },
      { nombre: "HARINA 0000", cantidad: 0.022 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.001 },
      { nombre: "HUEVOS", cantidad: 0.005 },
      { nombre: "MARGARINA", cantidad: 0.011 },
      { nombre: "DLECHE REPOSTERO PERGAMINO", cantidad: 0.035 },
      { nombre: "ESENCIA DE VAINILLA", cantidad: 0.0 },
      { nombre: "COBERTURA AMARGA EN POLVO", cantidad: 0.006 }
    ]
  },
  {
    mercaderia: "BUDIN BANANA",
    ingredientes: [
      { nombre: "LIMON", cantidad: 0.002 },
      { nombre: "LECHE ENTERA", cantidad: 0.020 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.091 },
      { nombre: "BANANA", cantidad: 0.091 },
      { nombre: "HARINA 0000", cantidad: 0.091 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.003 },
      { nombre: "SAL FINA", cantidad: 0.007 },
      { nombre: "HUEVOS", cantidad: 0.057 },
      { nombre: "BUDINERA B60 DESCARTABLE", cantidad: 1.0 },
      { nombre: "ACEITE GIRASOL", cantidad: 0.036 }
    ]
  },
  {
    mercaderia: "CHOCOTORTA",
    ingredientes: [
      { nombre: "HARINA 0000", cantidad: 0.0081 },
      { nombre: "HUEVOS", cantidad: 0.0635 },
      { nombre: "MARGARINA", cantidad: 0.0049 },
      { nombre: "AZUCAR SUELTA", cantidad: 0.0016 },
      { nombre: "POLVO PARA HORNEAR", cantidad: 0.0 },
      { nombre: "QUESO UNTABLE", cantidad: 0.0181 },
      { nombre: "DULCE DE LECHE REPOSTERO", cantidad: 0.0270 },
      { nombre: "GELATINA BLOOM", cantidad: 0.0003 },
      { nombre: "CACAO AMARGO", cantidad: 0.0013 },
      { nombre: "MICROGALLETITAS", cantidad: 0.0032 }
    ]
  }
]