export const productos = [
  { codigo: "35", nombre: "Lechuga" },
  { codigo: "36", nombre: "Perejil" },
  { codigo: "39", nombre: "Tomates" },
  { codigo: "41", nombre: "Zanahorias" },
  { codigo: "47", nombre: "Limon" },
  { codigo: "61", nombre: "Leche entera" },
  { codigo: "63", nombre: "Ricotta" },
  { codigo: "64", nombre: "Crema de leche al 39%" },
  { codigo: "78", nombre: "Queso muzarella" },
  { codigo: "81", nombre: "Panceta salada" },
  { codigo: "82", nombre: "Fiambre cocido pata de cerdo" },
  { codigo: "83", nombre: "Jamon crudo" },
  { codigo: "86", nombre: "Salame milan" },
  { codigo: "87", nombre: "Salchichon c/jamon" },
  { codigo: "89", nombre: "Lomito (fiambre)" },
  { codigo: "91", nombre: "Queso en barra" },
  { codigo: "92", nombre: "Queso fresco" },
  { codigo: "97", nombre: "Leverbusrt" },
  { codigo: "98", nombre: "Chocolate en barra" },
  { codigo: "102", nombre: "Canela molida" },
  { codigo: "105", nombre: "Nuez moscada" },
  { codigo: "107", nombre: "Pimienta" },
  { codigo: "132", nombre: "Pan de hamburguesa" },
  { codigo: "151", nombre: "Oporto" },
  { codigo: "161", nombre: "Papel sulfito" },
  { codigo: "170", nombre: "Tia maria" },
  { codigo: "225", nombre: "Manzana deshidratada" },
  { codigo: "233", nombre: "Nesquik" },
  { codigo: "257", nombre: "Azucar suelta" },
  { codigo: "261", nombre: "Caramelo liquido" },
  { codigo: "272", nombre: "Esencia de vainilla" },
  { codigo: "274", nombre: "Coco rallado" },
  { codigo: "285", nombre: "Gelatina cereza light" },
  { codigo: "289", nombre: "Harina 0000" },
  { codigo: "291", nombre: "Maizena" },
  { codigo: "305", nombre: "Polvo para hornear" },
  { codigo: "307", nombre: "Sal fina" },
  { codigo: "321", nombre: "Huevos" },
  { codigo: "322", nombre: "Mayonesa individual" },
  { codigo: "323", nombre: "Mayonesa" },
  { codigo: "327", nombre: "Queso rallado" },
  { codigo: "330", nombre: "Dulce membrillo" },
  { codigo: "331", nombre: "Dulce batata" },
  { codigo: "335", nombre: "Miel" },
  { codigo: "340", nombre: "Servilletas 33x33" },
  { codigo: "355", nombre: "Pote 101" },
  { codigo: "356", nombre: "Tapas 101" },
  { codigo: "375", nombre: "Postre ddl ligth" },
  { codigo: "396", nombre: "Azucar impalpable" },
  { codigo: "450", nombre: "Mayonesa pouch" },
  { codigo: "497", nombre: "Manzana verde" },
  { codigo: "571", nombre: "Galletita rumba" },
  { codigo: "639", nombre: "Fruta abrillantdas" },
  { codigo: "762", nombre: "Mortadela" },
  { codigo: "951", nombre: "Bandeja 618" },
  { codigo: "1044", nombre: "Flan de diet rendidor" },
  { codigo: "1113", nombre: "Margarina" },
  { codigo: "1605", nombre: "Queso untable" },
  { codigo: "1667", nombre: "Bandeja 619" },
  { codigo: "1930", nombre: "Sorbato de potasio" },
  { codigo: "1935", nombre: "Sopa crema de zapallo" },
  { codigo: "1943", nombre: "Mani por kilo" },
  { codigo: "2003", nombre: "V.crocante" },
  { codigo: "2149", nombre: "Cobertura amarga en polvo" },
  { codigo: "2167", nombre: "Pote 132" },
  { codigo: "2168", nombre: "Tapa aluminio" },
  { codigo: "2172", nombre: "Tapa aluminio verde" },
  { codigo: "2452", nombre: "Pebete" },
  { codigo: "2546", nombre: "Nuez pelada" },
  { codigo: "2547", nombre: "Almendras" },
  { codigo: "2730", nombre: "Manteca" },
  { codigo: "2743", nombre: "Chocolate cobertura blanco" },
  { codigo: "2748", nombre: "Pulpaliz" },
  { codigo: "3672", nombre: "Bandeja 650" },
  { codigo: "3751", nombre: "Semillas de amapola" },
  { codigo: "3974", nombre: "Azucar suelta" },
  { codigo: "3975", nombre: "Castañas de caju" },
  { codigo: "4017", nombre: "Pulpa de maracuya" },
  { codigo: "4226", nombre: "Café torrado molido" },
  { codigo: "4285", nombre: "Bolsas 50x70" },
  { codigo: "4297", nombre: "Papel folex" },
  { codigo: "4483", nombre: "Colorante rojo 1009" },
  { codigo: "4484", nombre: "Balde de helado 10 l" },
  { codigo: "4518", nombre: "Dulce de leche heladero 10 kg" },
  { codigo: "4557", nombre: "Semolin de trigo" },
  { codigo: "4564", nombre: "Mayonesa" },
  { codigo: "4603", nombre: "Pionono" },
  { codigo: "4608", nombre: "Caja tortera" },
  { codigo: "4610", nombre: "Caja para ravioles" },
  { codigo: "4618", nombre: "Balde de helado 5l" },
  { codigo: "4624", nombre: "Neutro" },
  { codigo: "4635", nombre: "Pasas de uva rubia" },
  { codigo: "4680", nombre: "Pulpa de durazno" },
  { codigo: "4683", nombre: "Pulpa de anana" },
  { codigo: "4736", nombre: "Mix de frutos rojos congelados" },
  { codigo: "4763", nombre: "Frutillas congeladas" },
  { codigo: "4766", nombre: "Banana" },
  { codigo: "4773", nombre: "Microgalletitas" },
  { codigo: "4821", nombre: "Leche en polvo" },
  { codigo: "4827", nombre: "Postre de caramelo" },
  { codigo: "4853", nombre: "Milanesa de soja" },
  { codigo: "4959", nombre: "Dextrosa" },
  { codigo: "4960", nombre: "Cobertura amarga" },
  { codigo: "4965", nombre: "Esencia de frutilla" },
  { codigo: "4980", nombre: "Galleta molida" },
  { codigo: "4986", nombre: "Esencia de banana" },
  { codigo: "4989", nombre: "Aceite esencial de limon" },
  { codigo: "4991", nombre: "Sabor a galletita" },
  { codigo: "4992", nombre: "Colorante amarillo 1001" },
  { codigo: "4998", nombre: "Esencia de vainilla alfa" },
  { codigo: "5002", nombre: "Sabor a leche condensada" },
  { codigo: "5006", nombre: "Crema de leche al 44%" },
  { codigo: "5096", nombre: "Esencia de durazno" },
  { codigo: "5109", nombre: "Budinera aluminio" },
  { codigo: "5130", nombre: "Coloroante verde" },
  { codigo: "5166", nombre: "Postre vainilla light" },
  { codigo: "5167", nombre: "Postre chocolate light" },
  { codigo: "5222", nombre: "Limon l" },
  { codigo: "5384", nombre: "Variegato frutos rojos" },
  { codigo: "5532", nombre: "Esencia de coco" },
  { codigo: "5585", nombre: "Gelatina bloom" },
  { codigo: "5586", nombre: "Acido citrico" },
  { codigo: "5587", nombre: "Citrato trisodico" },
  { codigo: "5588", nombre: "Esencia de cereza" },
  { codigo: "5589", nombre: "Esencia de uva" },
  { codigo: "5591", nombre: "Colorante rojo amaranto" },
  { codigo: "5592", nombre: "Esencia de manzana" },
  { codigo: "5593", nombre: "Esencia de anana" },
  { codigo: "5612", nombre: "Dulce repostero" },
  { codigo: "5615", nombre: "Crema de leche pote familiar" },
  { codigo: "5968", nombre: "Goma xantica" },
  { codigo: "5969", nombre: "Goma guar" },
  { codigo: "5970", nombre: "Colorante tartrasina" },
  { codigo: "5972", nombre: "Vainilla firmenich" },
  { codigo: "5975", nombre: "Carragenina lactea" },
  { codigo: "6086", nombre: "Jugo de sabor tang" },
  { codigo: "7046", nombre: "Jarabe de glucosa" },
  { codigo: "7401", nombre: "Aceite de girasol" },
  { codigo: "7540", nombre: "Papel seda" },
  { codigo: "8110", nombre: "Galletitas vainillas" },
  { codigo: "8111", nombre: "Pionono de chocolate" },
  { codigo: "8541", nombre: "Bandeja grande de carton" },
  { codigo: "8632", nombre: "Pan para hamburguesa c/semillas" },
  { codigo: "8633", nombre: "Pan alargado c/sesamo" },
  { codigo: "8868", nombre: "Stracciatela blanca" },
  { codigo: "9551", nombre: "Pasta de gianduia" },
  { codigo: "9668", nombre: "Jugo pvo bc manzana roja" },
  { codigo: "9734", nombre: "Dulce de leche vegetal" },
  { codigo: "9761", nombre: "Neutro five fruit" },
  { codigo: "9788", nombre: "Cubanitos" },
  { codigo: "9789", nombre: "Baño p/heladeria semiamargo" },
  { codigo: "10580", nombre: "Queso sardo" },
  { codigo: "10639", nombre: "Cajas de telgopor" },
  { codigo: "11190", nombre: "Pan de miga blanco" },
  { codigo: "30000", nombre: "Pasta de mani" },
  { codigo: "30072", nombre: "Leche de coco" },
  { codigo: "30376", nombre: "Ricota castelar" },
  { codigo: "30379", nombre: "Pan ciabata" },
  { codigo: "30381", nombre: "Pan bagel multicereal" }
];